//! Canonical SQLite schema for AetherEdge.
//!
//! Owns the DDL constants, revision/integrity triggers and bootstrap helpers
//! that define the on-disk schema. This is the single source of truth: service
//! startup paths, `aether-config` re-exports and the `aether` CLI all read
//! these definitions, and tests use the same `init_*_schema` helpers so that
//! fixtures cannot drift from production DDL.
//!
//! The five IO tables are derived from the private record structs below rather
//! than written out by hand. `aether-config` previously carried a second,
//! generated copy of the same five tables and the two had drifted: the
//! hand-written text had dropped `NOT NULL` from every `scale`, `offset` and
//! `reverse` column, so `aether sync` provisioned a laxer schema than the one
//! `aether-io`'s tests ran against. Keeping the derivation here is what makes
//! that class of drift unrepresentable.
//!
//! # Usage
//!
//! ```rust,ignore
//! use common::schema;
//! use sqlx::SqlitePool;
//!
//! let pool = SqlitePool::connect("sqlite::memory:").await?;
//! schema::init_io_schema(&pool).await?;
//! ```

use aether_schema_macro::Schema;
use anyhow::Result;
use sqlx::SqlitePool;

// Re-export common table constants
pub use crate::{SERVICE_CONFIG_TABLE, SYNC_METADATA_TABLE};

// ============================================================================
// Io Table DDL
// ============================================================================

/// Channels table record
/// Stores channel configurations - Maps to ChannelConfig structure
#[allow(dead_code)]
#[derive(Schema)]
#[table(
    name = "channels",
    suffix = "CHECK (TYPEOF(revision) = 'integer' AND revision >= 1), CHECK (channel_id >= 1 AND channel_id < 10000)"
)]
struct ChannelRecord {
    #[column(primary_key)]
    channel_id: u32,

    #[column(not_null, unique)]
    name: String,

    protocol: Option<String>,

    #[column(default = "false")]
    enabled: bool,

    config: Option<String>, // JSON TEXT

    /// Monotonic desired-state revision. Every authoritative writer must
    /// advance this value explicitly.
    #[column(default = "1")]
    revision: i64,

    #[column(default = "CURRENT_TIMESTAMP")]
    created_at: String, // TIMESTAMP type

    #[column(default = "CURRENT_TIMESTAMP")]
    updated_at: String, // TIMESTAMP type
}

/// Channels table SQL (generated by Schema macro)
pub const CHANNELS_TABLE: &str = ChannelRecord::CREATE_TABLE_SQL;

/// Durable per-identity high-water mark retained after channel deletion.
///
/// A recreated channel must advance beyond this value so a CAS token issued
/// for a deleted entity can never match the new entity (ABA protection).
pub const CHANNEL_REVISION_TOMBSTONES_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS channel_revision_tombstones (
        channel_id INTEGER NOT NULL PRIMARY KEY
            CHECK (channel_id >= 1 AND channel_id < 10000),
        last_revision INTEGER NOT NULL
            CHECK (TYPEOF(last_revision) = 'integer' AND last_revision >= 1),
        deleted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
"#;

/// Reject authoritative updates that omit an explicit revision advance.
pub const CHANNEL_REVISION_UPDATE_GUARD_TRIGGER: &str = r#"
    CREATE TRIGGER IF NOT EXISTS require_channel_revision_on_update
    BEFORE UPDATE OF name, protocol, enabled, config ON channels
    FOR EACH ROW
    WHEN NEW.revision = OLD.revision
    BEGIN
        SELECT RAISE(ABORT, 'channel update requires explicit revision');
    END
"#;

/// Require every revision change to advance by exactly one integer step.
pub const CHANNEL_REVISION_STEP_GUARD_TRIGGER: &str = r#"
    CREATE TRIGGER IF NOT EXISTS require_next_channel_revision
    BEFORE UPDATE OF revision ON channels
    FOR EACH ROW
    WHEN NEW.revision != OLD.revision + 1
      OR OLD.revision >= 9223372036854775807
    BEGIN
        SELECT RAISE(ABORT, 'channel revision must advance by exactly one');
    END
"#;

/// Require a recreated channel to supply a revision beyond its tombstone.
pub const CHANNEL_REVISION_INSERT_GUARD_TRIGGER: &str = r#"
    CREATE TRIGGER IF NOT EXISTS require_fresh_channel_revision_on_recreate
    BEFORE INSERT ON channels
    FOR EACH ROW
    WHEN EXISTS (
        SELECT 1 FROM channel_revision_tombstones
        WHERE channel_id = NEW.channel_id
          AND NEW.revision <= last_revision
    )
    BEGIN
        SELECT RAISE(ABORT, 'channel revision must advance beyond tombstone');
    END
"#;

/// Require deletion to be preceded by a higher durable tombstone revision.
pub const CHANNEL_REVISION_DELETE_GUARD_TRIGGER: &str = r#"
    CREATE TRIGGER IF NOT EXISTS require_channel_delete_tombstone
    BEFORE DELETE ON channels
    FOR EACH ROW
    WHEN NOT EXISTS (
        SELECT 1 FROM channel_revision_tombstones
        WHERE channel_id = OLD.channel_id
          AND last_revision > OLD.revision
    )
    BEGIN
        SELECT RAISE(ABORT, 'channel delete requires prepared revision tombstone');
    END
"#;

/// Reject invalid channel identities on databases created before the table
/// check became mandatory.
pub const CHANNEL_ID_INSERT_GUARD_TRIGGER: &str = r#"
    CREATE TRIGGER IF NOT EXISTS require_valid_channel_id_on_insert
    BEFORE INSERT ON channels
    FOR EACH ROW
    WHEN NEW.channel_id < 1 OR NEW.channel_id >= 10000
    BEGIN
        SELECT RAISE(ABORT, 'channel identity must be between 1 and 9999');
    END
"#;

/// Prevent primary-key migration to an invalid channel identity.
pub const CHANNEL_ID_UPDATE_GUARD_TRIGGER: &str = r#"
    CREATE TRIGGER IF NOT EXISTS require_valid_channel_id_on_update
    BEFORE UPDATE OF channel_id ON channels
    FOR EACH ROW
    WHEN NEW.channel_id < 1 OR NEW.channel_id >= 10000
    BEGIN
        SELECT RAISE(ABORT, 'channel identity must be between 1 and 9999');
    END
"#;

/// Trigger names removed when upgrading from automatic revision repair.
pub const OBSOLETE_CHANNEL_REVISION_TRIGGER_NAMES: &[&str] = &[
    "reject_exhausted_channel_revision",
    "bump_channel_revision",
    "reject_exhausted_channel_revision_on_recreate",
    "advance_channel_revision_on_recreate",
    "reject_exhausted_channel_revision_on_delete",
    "tombstone_channel_revision_on_delete",
];

/// Install the fail-closed channel revision and tombstone guards.
pub async fn install_channel_revision_guards(pool: &SqlitePool) -> Result<()> {
    sqlx::query(CHANNEL_REVISION_TOMBSTONES_TABLE)
        .execute(pool)
        .await?;
    for trigger in OBSOLETE_CHANNEL_REVISION_TRIGGER_NAMES {
        sqlx::query(&format!("DROP TRIGGER IF EXISTS {trigger}"))
            .execute(pool)
            .await?;
    }
    sqlx::query(CHANNEL_REVISION_UPDATE_GUARD_TRIGGER)
        .execute(pool)
        .await?;
    sqlx::query(CHANNEL_REVISION_STEP_GUARD_TRIGGER)
        .execute(pool)
        .await?;
    sqlx::query(CHANNEL_REVISION_INSERT_GUARD_TRIGGER)
        .execute(pool)
        .await?;
    sqlx::query(CHANNEL_REVISION_DELETE_GUARD_TRIGGER)
        .execute(pool)
        .await?;
    sqlx::query(CHANNEL_ID_INSERT_GUARD_TRIGGER)
        .execute(pool)
        .await?;
    sqlx::query(CHANNEL_ID_UPDATE_GUARD_TRIGGER)
        .execute(pool)
        .await?;
    Ok(())
}

/// Telemetry points table record
/// Stores analog measurement points with embedded protocol mappings as JSON
#[allow(dead_code)]
#[derive(Schema)]
#[table(
    name = "telemetry_points",
    suffix = "PRIMARY KEY (channel_id, point_id)"
)]
struct TelemetryPointRecord {
    #[column(not_null)]
    point_id: u32,

    #[column(not_null, references = "channels(channel_id)", on_delete = "CASCADE")]
    channel_id: u32,

    #[column(not_null)]
    signal_name: String,

    #[column(default = "1.0")]
    scale: f64,

    #[column(default = "0.0")]
    offset: f64,

    unit: Option<String>,

    #[column(default = "false")]
    reverse: bool,

    data_type: Option<String>,

    description: Option<String>,

    protocol_mappings: Option<String>, // JSON TEXT
}

/// Telemetry points table SQL (generated by Schema macro)
pub const TELEMETRY_POINTS_TABLE: &str = TelemetryPointRecord::CREATE_TABLE_SQL;

/// Signal points table record
/// Stores digital/binary status points with embedded protocol mappings as JSON
#[allow(dead_code)]
#[derive(Schema)]
#[table(name = "signal_points", suffix = "PRIMARY KEY (channel_id, point_id)")]
struct SignalPointRecord {
    #[column(not_null)]
    point_id: u32,

    #[column(not_null, references = "channels(channel_id)", on_delete = "CASCADE")]
    channel_id: u32,

    #[column(not_null)]
    signal_name: String,

    #[column(default = "1.0")]
    scale: f64,

    #[column(default = "0.0")]
    offset: f64,

    unit: Option<String>,

    #[column(default = "false")]
    reverse: bool,

    #[column(default = "0")]
    normal_state: i32,

    data_type: Option<String>,

    description: Option<String>,

    protocol_mappings: Option<String>, // JSON TEXT
}

/// Signal points table SQL (generated by Schema macro)
pub const SIGNAL_POINTS_TABLE: &str = SignalPointRecord::CREATE_TABLE_SQL;

/// Control points table record
/// Stores remote control command points with embedded protocol mappings as JSON
#[allow(dead_code)]
#[derive(Schema)]
#[table(name = "control_points", suffix = "PRIMARY KEY (channel_id, point_id)")]
struct ControlPointRecord {
    #[column(not_null)]
    point_id: u32,

    #[column(not_null, references = "channels(channel_id)", on_delete = "CASCADE")]
    channel_id: u32,

    #[column(not_null)]
    signal_name: String,

    #[column(default = "1.0")]
    scale: f64,

    #[column(default = "0.0")]
    offset: f64,

    unit: Option<String>,

    #[column(default = "false")]
    reverse: bool,

    data_type: Option<String>,

    description: Option<String>,

    protocol_mappings: Option<String>, // JSON TEXT
}

/// Control points table SQL (generated by Schema macro)
pub const CONTROL_POINTS_TABLE: &str = ControlPointRecord::CREATE_TABLE_SQL;

/// Adjustment points table record
/// Stores remote setpoint adjustment points with embedded protocol mappings as JSON
#[allow(dead_code)]
#[derive(Schema)]
#[table(
    name = "adjustment_points",
    suffix = "PRIMARY KEY (channel_id, point_id)"
)]
struct AdjustmentPointRecord {
    #[column(not_null)]
    point_id: u32,

    #[column(not_null, references = "channels(channel_id)", on_delete = "CASCADE")]
    channel_id: u32,

    #[column(not_null)]
    signal_name: String,

    #[column(default = "1.0")]
    scale: f64,

    #[column(default = "0.0")]
    offset: f64,

    unit: Option<String>,

    #[column(default = "false")]
    reverse: bool,

    data_type: Option<String>,

    description: Option<String>,

    protocol_mappings: Option<String>, // JSON TEXT

    min_value: Option<f64>,

    max_value: Option<f64>,

    #[column(default = "1.0")]
    step: f64,
}

/// Adjustment points table SQL (generated by Schema macro)
pub const ADJUSTMENT_POINTS_TABLE: &str = AdjustmentPointRecord::CREATE_TABLE_SQL;

/// Channel routing table record (C2C routing)
/// Stores direct channel-to-channel data forwarding rules
#[allow(dead_code)]
#[derive(Schema)]
#[table(
    name = "channel_routing",
    suffix = "PRIMARY KEY (source_channel_id, source_type, source_point_id)"
)]
struct ChannelRoutingRecord {
    #[column(not_null, references = "channels(channel_id)")]
    source_channel_id: u32,

    #[column(not_null)]
    source_type: String, // T/S/C/A

    #[column(not_null)]
    source_point_id: u32,

    #[column(not_null, references = "channels(channel_id)")]
    target_channel_id: u32,

    #[column(not_null)]
    target_type: String, // T/S/C/A

    #[column(not_null)]
    target_point_id: u32,

    #[column(default = "true")]
    enabled: bool,

    #[column(default = "1.0")]
    scale: f64,

    #[column(default = "0.0")]
    offset: f64,

    description: Option<String>,

    #[column(default = "CURRENT_TIMESTAMP")]
    created_at: String, // TIMESTAMP type

    #[column(default = "CURRENT_TIMESTAMP")]
    updated_at: String, // TIMESTAMP type
}

// Schema SQL constant
pub const CHANNEL_ROUTING_TABLE: &str = ChannelRoutingRecord::CREATE_TABLE_SQL;

// ============================================================================
// Channel Templates DDL
// ============================================================================

/// Channel templates table DDL — stores point configuration snapshots as JSON
///
/// Templates capture a channel's complete point definitions and protocol mappings,
/// enabling "save once → apply many" workflows for devices with identical configurations.
pub const CHANNEL_TEMPLATES_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS channel_templates (
        template_id       INTEGER PRIMARY KEY AUTOINCREMENT,
        name              TEXT NOT NULL UNIQUE,
        description       TEXT,
        protocol          TEXT NOT NULL,
        points_snapshot   TEXT NOT NULL,
        mappings_snapshot TEXT NOT NULL,
        source_channel_id INTEGER REFERENCES channels(channel_id) ON DELETE SET NULL,
        created_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
"#;

/// Index on channel_templates.source_channel_id — accelerates lookups by source
/// channel and lets `ON DELETE SET NULL` cascade cheaply.
pub const CHANNEL_TEMPLATES_SOURCE_INDEX: &str = "CREATE INDEX IF NOT EXISTS idx_channel_templates_source ON channel_templates(source_channel_id)";

// ============================================================================
// Automation Table DDL (matches automation::config schemas)
// ============================================================================

/// Instances table DDL (matches automation::config::InstanceRecord)
/// Note: No foreign key to products table - products are compile-time constants
pub const INSTANCES_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS instances (
        instance_id INTEGER NOT NULL PRIMARY KEY,
        instance_name TEXT NOT NULL UNIQUE,
        product_name TEXT NOT NULL,
        parent_id INTEGER,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (parent_id) REFERENCES instances(instance_id) ON DELETE SET NULL
    )
"#;

/// Measurement routing table DDL (matches automation::config::MeasurementRoutingRecord)
pub const MEASUREMENT_ROUTING_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS measurement_routing (
        routing_id INTEGER PRIMARY KEY AUTOINCREMENT,
        instance_id INTEGER NOT NULL REFERENCES instances(instance_id) ON DELETE CASCADE,
        instance_name TEXT NOT NULL,
        channel_id INTEGER REFERENCES channels(channel_id) ON DELETE SET NULL,
        channel_type TEXT,
        channel_point_id INTEGER,
        measurement_id INTEGER NOT NULL,
        description TEXT,
        enabled INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(instance_id, measurement_id),
        CHECK(channel_type IN ('T','S'))
    )
"#;

/// Shared compare-and-set heads for authoritative configuration aggregates.
pub const CONFIGURATION_REVISIONS_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS configuration_revisions (
        scope TEXT NOT NULL PRIMARY KEY CHECK (length(trim(scope)) > 0),
        revision INTEGER NOT NULL
            CHECK (TYPEOF(revision) = 'integer' AND revision >= 1),
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
"#;

/// Ensures canonical CAS heads exist for online configuration aggregates.
pub async fn initialize_configuration_revisions(pool: &SqlitePool) -> Result<()> {
    sqlx::query(CONFIGURATION_REVISIONS_TABLE)
        .execute(pool)
        .await?;
    sqlx::query(
        "INSERT INTO configuration_revisions (scope, revision) \
         VALUES ('logical_routing', 1) ON CONFLICT(scope) DO NOTHING",
    )
    .execute(pool)
    .await?;
    sqlx::query(
        "INSERT INTO configuration_revisions (scope, revision) \
         VALUES ('automation_rules', 1) ON CONFLICT(scope) DO NOTHING",
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Action routing table DDL (matches automation::config::ActionRoutingRecord)
pub const ACTION_ROUTING_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS action_routing (
        routing_id INTEGER PRIMARY KEY AUTOINCREMENT,
        instance_id INTEGER NOT NULL REFERENCES instances(instance_id) ON DELETE CASCADE,
        instance_name TEXT NOT NULL,
        action_id INTEGER NOT NULL,
        channel_id INTEGER REFERENCES channels(channel_id) ON DELETE SET NULL,
        channel_type TEXT,
        channel_point_id INTEGER,
        description TEXT,
        enabled INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(instance_id, action_id),
        CHECK(channel_type IN ('C','A'))
    )
"#;

// ============================================================================
// Logical Routing Integrity Triggers
// ============================================================================

/// Names of the routing-integrity triggers installed in the unified database.
///
/// Production initialization drops these names before reinstalling them so an
/// already initialized database cannot retain an older trigger definition.
pub const LOGICAL_ROUTING_INTEGRITY_TRIGGER_NAMES: &[&str] = &[
    "validate_measurement_routing_target_on_insert",
    "validate_measurement_routing_target_on_update",
    "validate_action_routing_target_on_insert",
    "validate_action_routing_target_on_update",
    "protect_measurement_routing_on_telemetry_delete",
    "protect_measurement_routing_on_telemetry_identity_update",
    "protect_measurement_routing_on_signal_delete",
    "protect_measurement_routing_on_signal_identity_update",
    "protect_action_routing_on_control_delete",
    "protect_action_routing_on_control_identity_update",
    "protect_action_routing_on_adjustment_delete",
    "protect_action_routing_on_adjustment_identity_update",
    "protect_measurement_routing_on_channel_delete",
    "protect_measurement_routing_on_instance_delete",
    "protect_action_routing_on_channel_delete",
    "protect_action_routing_on_instance_delete",
];

/// Canonical DDL for the logical-routing integrity triggers.
///
/// Exposed for the unified-schema migration that must temporarily remove and
/// restore these triggers while rebuilding physical point tables.
pub const LOGICAL_ROUTING_INTEGRITY_TRIGGERS: &[&str] = &[
    r#"
    CREATE TRIGGER IF NOT EXISTS validate_measurement_routing_target_on_insert
    BEFORE INSERT ON measurement_routing
    FOR EACH ROW
    WHEN NOT EXISTS (
             SELECT 1 FROM instances
             WHERE instance_id = NEW.instance_id
               AND instance_name = NEW.instance_name
         )
      OR NEW.channel_id IS NULL
      OR NEW.channel_type IS NULL
      OR NEW.channel_point_id IS NULL
      OR (NEW.channel_type = 'T' AND NOT EXISTS (
             SELECT 1 FROM telemetry_points
             WHERE channel_id = NEW.channel_id AND point_id = NEW.channel_point_id
         ))
      OR (NEW.channel_type = 'S' AND NOT EXISTS (
             SELECT 1 FROM signal_points
             WHERE channel_id = NEW.channel_id AND point_id = NEW.channel_point_id
         ))
      OR NEW.channel_type NOT IN ('T', 'S')
    BEGIN
        SELECT RAISE(ABORT, 'measurement route requires a matching instance and T/S physical target');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS validate_measurement_routing_target_on_update
    BEFORE UPDATE OF instance_id, instance_name, measurement_id, channel_id, channel_type, channel_point_id
    ON measurement_routing
    FOR EACH ROW
    WHEN NOT EXISTS (
             SELECT 1 FROM instances
             WHERE instance_id = NEW.instance_id
               AND instance_name = NEW.instance_name
         )
      OR NEW.channel_id IS NULL
      OR NEW.channel_type IS NULL
      OR NEW.channel_point_id IS NULL
      OR (NEW.channel_type = 'T' AND NOT EXISTS (
             SELECT 1 FROM telemetry_points
             WHERE channel_id = NEW.channel_id AND point_id = NEW.channel_point_id
         ))
      OR (NEW.channel_type = 'S' AND NOT EXISTS (
             SELECT 1 FROM signal_points
             WHERE channel_id = NEW.channel_id AND point_id = NEW.channel_point_id
         ))
      OR NEW.channel_type NOT IN ('T', 'S')
    BEGIN
        SELECT RAISE(ABORT, 'measurement route requires a matching instance and T/S physical target');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS validate_action_routing_target_on_insert
    BEFORE INSERT ON action_routing
    FOR EACH ROW
    WHEN NOT EXISTS (
             SELECT 1 FROM instances
             WHERE instance_id = NEW.instance_id
               AND instance_name = NEW.instance_name
         )
      OR NEW.channel_id IS NULL
      OR NEW.channel_type IS NULL
      OR NEW.channel_point_id IS NULL
      OR (NEW.channel_type = 'C' AND NOT EXISTS (
             SELECT 1 FROM control_points
             WHERE channel_id = NEW.channel_id AND point_id = NEW.channel_point_id
         ))
      OR (NEW.channel_type = 'A' AND NOT EXISTS (
             SELECT 1 FROM adjustment_points
             WHERE channel_id = NEW.channel_id AND point_id = NEW.channel_point_id
         ))
      OR NEW.channel_type NOT IN ('C', 'A')
    BEGIN
        SELECT RAISE(ABORT, 'action route requires a matching instance and C/A physical target');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS validate_action_routing_target_on_update
    BEFORE UPDATE OF instance_id, instance_name, action_id, channel_id, channel_type, channel_point_id
    ON action_routing
    FOR EACH ROW
    WHEN NOT EXISTS (
             SELECT 1 FROM instances
             WHERE instance_id = NEW.instance_id
               AND instance_name = NEW.instance_name
         )
      OR NEW.channel_id IS NULL
      OR NEW.channel_type IS NULL
      OR NEW.channel_point_id IS NULL
      OR (NEW.channel_type = 'C' AND NOT EXISTS (
             SELECT 1 FROM control_points
             WHERE channel_id = NEW.channel_id AND point_id = NEW.channel_point_id
         ))
      OR (NEW.channel_type = 'A' AND NOT EXISTS (
             SELECT 1 FROM adjustment_points
             WHERE channel_id = NEW.channel_id AND point_id = NEW.channel_point_id
         ))
      OR NEW.channel_type NOT IN ('C', 'A')
    BEGIN
        SELECT RAISE(ABORT, 'action route requires a matching instance and C/A physical target');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_measurement_routing_on_telemetry_delete
    BEFORE DELETE ON telemetry_points
    FOR EACH ROW
    WHEN EXISTS (
        SELECT 1 FROM measurement_routing
        WHERE channel_id = OLD.channel_id
          AND channel_type = 'T'
          AND channel_point_id = OLD.point_id
    )
    BEGIN
        SELECT RAISE(ABORT, 'use the governed measurement-routing command before deleting a measurement target');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_measurement_routing_on_telemetry_identity_update
    BEFORE UPDATE OF channel_id, point_id ON telemetry_points
    FOR EACH ROW
    WHEN (NEW.channel_id IS NOT OLD.channel_id OR NEW.point_id IS NOT OLD.point_id)
     AND EXISTS (
        SELECT 1 FROM measurement_routing
        WHERE channel_id = OLD.channel_id
          AND channel_type = 'T'
          AND channel_point_id = OLD.point_id
    )
    BEGIN
        SELECT RAISE(ABORT, 'use the governed measurement-routing command before changing a measurement target identity');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_measurement_routing_on_signal_delete
    BEFORE DELETE ON signal_points
    FOR EACH ROW
    WHEN EXISTS (
        SELECT 1 FROM measurement_routing
        WHERE channel_id = OLD.channel_id
          AND channel_type = 'S'
          AND channel_point_id = OLD.point_id
    )
    BEGIN
        SELECT RAISE(ABORT, 'use the governed measurement-routing command before deleting a measurement target');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_measurement_routing_on_signal_identity_update
    BEFORE UPDATE OF channel_id, point_id ON signal_points
    FOR EACH ROW
    WHEN (NEW.channel_id IS NOT OLD.channel_id OR NEW.point_id IS NOT OLD.point_id)
     AND EXISTS (
        SELECT 1 FROM measurement_routing
        WHERE channel_id = OLD.channel_id
          AND channel_type = 'S'
          AND channel_point_id = OLD.point_id
    )
    BEGIN
        SELECT RAISE(ABORT, 'use the governed measurement-routing command before changing a measurement target identity');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_action_routing_on_control_delete
    BEFORE DELETE ON control_points
    FOR EACH ROW
    WHEN EXISTS (
        SELECT 1 FROM action_routing
        WHERE channel_id = OLD.channel_id
          AND channel_type = 'C'
          AND channel_point_id = OLD.point_id
    )
    BEGIN
        SELECT RAISE(ABORT, 'use the governed action-routing command before deleting an action target');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_action_routing_on_control_identity_update
    BEFORE UPDATE OF channel_id, point_id ON control_points
    FOR EACH ROW
    WHEN (NEW.channel_id IS NOT OLD.channel_id OR NEW.point_id IS NOT OLD.point_id)
     AND EXISTS (
        SELECT 1 FROM action_routing
        WHERE channel_id = OLD.channel_id
          AND channel_type = 'C'
          AND channel_point_id = OLD.point_id
    )
    BEGIN
        SELECT RAISE(ABORT, 'use the governed action-routing command before changing an action target identity');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_action_routing_on_adjustment_delete
    BEFORE DELETE ON adjustment_points
    FOR EACH ROW
    WHEN EXISTS (
        SELECT 1 FROM action_routing
        WHERE channel_id = OLD.channel_id
          AND channel_type = 'A'
          AND channel_point_id = OLD.point_id
    )
    BEGIN
        SELECT RAISE(ABORT, 'use the governed action-routing command before deleting an action target');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_action_routing_on_adjustment_identity_update
    BEFORE UPDATE OF channel_id, point_id ON adjustment_points
    FOR EACH ROW
    WHEN (NEW.channel_id IS NOT OLD.channel_id OR NEW.point_id IS NOT OLD.point_id)
     AND EXISTS (
        SELECT 1 FROM action_routing
        WHERE channel_id = OLD.channel_id
          AND channel_type = 'A'
          AND channel_point_id = OLD.point_id
    )
    BEGIN
        SELECT RAISE(ABORT, 'use the governed action-routing command before changing an action target identity');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_measurement_routing_on_channel_delete
    BEFORE DELETE ON channels
    FOR EACH ROW
    WHEN EXISTS (SELECT 1 FROM measurement_routing WHERE channel_id = OLD.channel_id)
    BEGIN
        SELECT RAISE(ABORT, 'use the governed measurement-routing command before deleting a measurement channel');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_measurement_routing_on_instance_delete
    BEFORE DELETE ON instances
    FOR EACH ROW
    WHEN EXISTS (SELECT 1 FROM measurement_routing WHERE instance_id = OLD.instance_id)
    BEGIN
        SELECT RAISE(ABORT, 'use the governed measurement-routing command before deleting a measurement instance');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_action_routing_on_channel_delete
    BEFORE DELETE ON channels
    FOR EACH ROW
    WHEN EXISTS (SELECT 1 FROM action_routing WHERE channel_id = OLD.channel_id)
    BEGIN
        SELECT RAISE(ABORT, 'use the governed action-routing command before deleting an action channel');
    END
    "#,
    r#"
    CREATE TRIGGER IF NOT EXISTS protect_action_routing_on_instance_delete
    BEFORE DELETE ON instances
    FOR EACH ROW
    WHEN EXISTS (SELECT 1 FROM action_routing WHERE instance_id = OLD.instance_id)
    BEGIN
        SELECT RAISE(ABORT, 'use the governed action-routing command before deleting an action instance');
    END
    "#,
];

/// Installs fail-closed referential integrity for the logical-routing tables.
///
/// Call this only after `channels`, all four physical point tables,
/// `instances`, and both routing tables have been created. The split IO and
/// automation test-schema helpers cannot install it independently because
/// neither owns that complete unified schema.
pub async fn install_logical_routing_integrity_triggers(pool: &SqlitePool) -> Result<()> {
    for trigger in LOGICAL_ROUTING_INTEGRITY_TRIGGERS {
        sqlx::query(trigger).execute(pool).await?;
    }
    Ok(())
}

/// Instance property values table DDL
///
/// One row per (instance_id, property_id). `value_json` holds the property's
/// current value as a JSON-encoded string (any JSON type is accepted —
/// number, string, bool, null, object, array). `property_id` references the
/// PropertyTemplate declared by the instance's product (a compile-time
/// selected Pack product catalog, so no foreign key is possible —
/// handlers validate the id against the template).
pub const INSTANCE_PROPERTIES_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS instance_properties (
        instance_id INTEGER NOT NULL REFERENCES instances(instance_id) ON DELETE CASCADE,
        property_id INTEGER NOT NULL,
        value_json  TEXT    NOT NULL,
        updated_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (instance_id, property_id)
    )
"#;

// ============================================================================
// Rules Table DDL
// ============================================================================

/// Rule chains table DDL (Vue Flow format).
///
/// `id` uses AUTOINCREMENT to prevent SQLite from reusing rowids of deleted
/// rules — otherwise rule_history rows referencing a deleted rule could be
/// silently re-bound to a new rule with the same id.
pub const RULE_CHAINS_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS rules (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        description TEXT,
        enabled INTEGER DEFAULT 1,
        priority INTEGER DEFAULT 0,
        cooldown_ms INTEGER DEFAULT 0,
        trigger_config TEXT,
        nodes_json TEXT NOT NULL,
        flow_json TEXT,
        format TEXT DEFAULT 'vue-flow',
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
"#;

/// Rule history table DDL — `rule_id` cascades so deleting a rule purges its
/// historical execution records (no orphaned history rows).
pub const RULE_HISTORY_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS rule_history (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        rule_id INTEGER NOT NULL REFERENCES rules(id) ON DELETE CASCADE,
        triggered_at TEXT NOT NULL,
        execution_result TEXT,
        error TEXT
    )
"#;

// ============================================================================
// Schema Initialization Functions
// ============================================================================

/// Initialize io standard schema for testing
///
/// Creates all io-related tables.
/// This includes:
/// - service_config
/// - sync_metadata
/// - channels
/// - telemetry_points, signal_points, control_points, adjustment_points
pub async fn init_io_schema(pool: &SqlitePool) -> Result<()> {
    // Service metadata tables
    sqlx::query(SERVICE_CONFIG_TABLE).execute(pool).await?;
    sqlx::query(SYNC_METADATA_TABLE).execute(pool).await?;

    // Core channel table
    sqlx::query(CHANNELS_TABLE).execute(pool).await?;
    install_channel_revision_guards(pool).await?;

    // Point tables
    sqlx::query(TELEMETRY_POINTS_TABLE).execute(pool).await?;
    sqlx::query(SIGNAL_POINTS_TABLE).execute(pool).await?;
    sqlx::query(CONTROL_POINTS_TABLE).execute(pool).await?;
    sqlx::query(ADJUSTMENT_POINTS_TABLE).execute(pool).await?;

    // Channel templates table
    sqlx::query(CHANNEL_TEMPLATES_TABLE).execute(pool).await?;
    sqlx::query(CHANNEL_TEMPLATES_SOURCE_INDEX)
        .execute(pool)
        .await?;

    Ok(())
}

/// Initialize automation standard schema for testing
///
/// Creates all automation-related tables.
/// This includes:
/// - service_config
/// - sync_metadata
/// - channels (required by routing table foreign keys)
/// - instances
/// - measurement_routing, action_routing
///
/// No products table is created. Product definitions come from validated active
/// Packs and an optional site directory at runtime.
pub async fn init_automation_schema(pool: &SqlitePool) -> Result<()> {
    // Service metadata tables
    sqlx::query(SERVICE_CONFIG_TABLE).execute(pool).await?;
    sqlx::query(SYNC_METADATA_TABLE).execute(pool).await?;

    // Channels table (required by routing table foreign keys in unified database architecture)
    sqlx::query(CHANNELS_TABLE).execute(pool).await?;
    install_channel_revision_guards(pool).await?;

    // Instance table (no longer references products table)
    sqlx::query(INSTANCES_TABLE).execute(pool).await?;

    // Routing tables
    sqlx::query(MEASUREMENT_ROUTING_TABLE).execute(pool).await?;
    sqlx::query(ACTION_ROUTING_TABLE).execute(pool).await?;
    initialize_configuration_revisions(pool).await?;

    // Instance property values (one row per property)
    sqlx::query(INSTANCE_PROPERTIES_TABLE).execute(pool).await?;

    Ok(())
}

/// Initialize rules standard schema for testing
///
/// Creates all rules-related tables.
/// This includes:
/// - service_config
/// - sync_metadata
/// - rules (Vue Flow rule chains)
/// - rule_history
pub async fn init_rules_schema(pool: &SqlitePool) -> Result<()> {
    // Service metadata tables
    sqlx::query(SERVICE_CONFIG_TABLE).execute(pool).await?;
    sqlx::query(SYNC_METADATA_TABLE).execute(pool).await?;

    // Rule chains table (Vue Flow format)
    sqlx::query(RULE_CHAINS_TABLE).execute(pool).await?;
    sqlx::query(RULE_HISTORY_TABLE).execute(pool).await?;
    initialize_configuration_revisions(pool).await?;

    Ok(())
}

#[cfg(test)]
#[allow(clippy::disallowed_methods)] // Test code - unwrap is acceptable
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_init_io_schema() {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        init_io_schema(&pool).await.unwrap();

        // Verify tables exist by querying them
        let result: (i64,) =
            sqlx::query_as("SELECT COUNT(*) FROM sqlite_master WHERE type='table'")
                .fetch_one(&pool)
                .await
                .unwrap();

        // Should have 8 tables: service_config, sync_metadata, channels, 4 point tables, channel_templates
        assert!(
            result.0 >= 8,
            "Expected at least 8 tables, found {}",
            result.0
        );

        for table in [
            "telemetry_points",
            "signal_points",
            "control_points",
            "adjustment_points",
        ] {
            let on_delete: String = sqlx::query_scalar(&format!(
                "SELECT on_delete FROM pragma_foreign_key_list('{table}') \
                 WHERE \"table\" = 'channels' \
                   AND \"from\" = 'channel_id' \
                   AND \"to\" = 'channel_id'"
            ))
            .fetch_one(&pool)
            .await
            .unwrap();
            assert_eq!(on_delete, "CASCADE", "wrong delete action for {table}");
        }

        let zero = sqlx::query(
            "INSERT INTO channels (channel_id, name, protocol, enabled, config) \
             VALUES (0, 'invalid-zero', 'modbus_tcp', 0, '{}')",
        )
        .execute(&pool)
        .await
        .expect_err("channel zero must fail");
        assert!(
            zero.to_string()
                .contains("channel identity must be between 1 and 9999")
        );

        let revision: i64 = sqlx::query_scalar(
            "INSERT INTO channels (channel_id, name, protocol, enabled, config) \
             VALUES (7, 'revision-contract', 'modbus_tcp', 0, '{}') \
             RETURNING revision",
        )
        .fetch_one(&pool)
        .await
        .unwrap();
        assert_eq!(revision, 1);

        let error = sqlx::query("UPDATE channels SET name = 'unrevisioned' WHERE channel_id = 7")
            .execute(&pool)
            .await
            .expect_err("unrevisioned channel update must fail");
        assert!(error.to_string().contains("requires explicit revision"));

        sqlx::query(
            "UPDATE channels SET name = 'governed-update', revision = revision + 1 \
             WHERE channel_id = 7",
        )
        .execute(&pool)
        .await
        .unwrap();
        let revision: i64 =
            sqlx::query_scalar("SELECT revision FROM channels WHERE channel_id = 7")
                .fetch_one(&pool)
                .await
                .unwrap();
        assert_eq!(revision, 2, "governed writes advance exactly once");
    }

    #[tokio::test]
    async fn channel_revision_guards_reject_unrevisioned_writers() {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        init_io_schema(&pool).await.unwrap();
        sqlx::query(
            "INSERT INTO channels (channel_id, name, protocol, enabled, config) \
             VALUES (7, 'revisioned-writer', 'modbus_tcp', 0, '{}')",
        )
        .execute(&pool)
        .await
        .unwrap();

        assert_eq!(
            sqlx::query_scalar::<_, i64>("SELECT revision FROM channels WHERE channel_id = 7")
                .fetch_one(&pool)
                .await
                .unwrap(),
            1
        );

        let error = sqlx::query("UPDATE channels SET name = 'unrevisioned' WHERE channel_id = 7")
            .execute(&pool)
            .await
            .expect_err("unrevisioned channel update must fail");
        assert!(error.to_string().contains("requires explicit revision"));
        assert_eq!(
            sqlx::query_scalar::<_, i64>("SELECT revision FROM channels WHERE channel_id = 7")
                .fetch_one(&pool)
                .await
                .unwrap(),
            1
        );

        sqlx::query(
            "UPDATE channels SET enabled = 1, revision = 2 \
             WHERE channel_id = 7 AND revision = 1",
        )
        .execute(&pool)
        .await
        .unwrap();
        assert_eq!(
            sqlx::query_scalar::<_, i64>("SELECT revision FROM channels WHERE channel_id = 7")
                .fetch_one(&pool)
                .await
                .unwrap(),
            2,
            "explicit CAS revision advances exactly once"
        );

        sqlx::query("UPDATE channels SET updated_at = '2099-01-01 00:00:00' WHERE channel_id = 7")
            .execute(&pool)
            .await
            .unwrap();
        assert_eq!(
            sqlx::query_scalar::<_, i64>("SELECT revision FROM channels WHERE channel_id = 7")
                .fetch_one(&pool)
                .await
                .unwrap(),
            2,
            "non-desired metadata updates must not bump revision"
        );

        sqlx::query(
            "INSERT INTO channels \
             (channel_id, name, protocol, enabled, config, revision) \
             VALUES (8, 'exhausted', 'modbus_tcp', 0, '{}', 9223372036854775807)",
        )
        .execute(&pool)
        .await
        .unwrap();
        let exhausted = sqlx::query(
            "UPDATE channels SET name = 'must-not-overflow', revision = revision + 1 \
             WHERE channel_id = 8",
        )
        .execute(&pool)
        .await
        .expect_err("exhausted revision must not overflow");
        assert!(
            exhausted
                .to_string()
                .contains("must advance by exactly one")
        );
        assert_eq!(
            sqlx::query_scalar::<_, i64>("SELECT revision FROM channels WHERE channel_id = 8")
                .fetch_one(&pool)
                .await
                .unwrap(),
            i64::MAX
        );
    }

    #[tokio::test]
    async fn channel_revision_tombstone_prevents_delete_recreate_aba() {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        init_io_schema(&pool).await.unwrap();
        sqlx::query(
            "INSERT INTO channels (channel_id, name, protocol, enabled, config) \
             VALUES (8, 'first-entity', 'modbus_tcp', 0, '{}')",
        )
        .execute(&pool)
        .await
        .unwrap();
        let error = sqlx::query("DELETE FROM channels WHERE channel_id = 8")
            .execute(&pool)
            .await
            .expect_err("direct channel delete must fail");
        assert!(
            error
                .to_string()
                .contains("requires prepared revision tombstone")
        );
        sqlx::query(
            "INSERT INTO channel_revision_tombstones (channel_id, last_revision) VALUES (8, 2)",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query("DELETE FROM channels WHERE channel_id = 8")
            .execute(&pool)
            .await
            .unwrap();
        assert_eq!(
            sqlx::query_scalar::<_, i64>(
                "SELECT last_revision FROM channel_revision_tombstones WHERE channel_id = 8",
            )
            .fetch_one(&pool)
            .await
            .unwrap(),
            2
        );

        let error = sqlx::query(
            "INSERT INTO channels (channel_id, name, protocol, enabled, config) \
             VALUES (8, 'stale-recreate', 'modbus_tcp', 0, '{}')",
        )
        .execute(&pool)
        .await
        .expect_err("recreate without a fresh revision must fail");
        assert!(error.to_string().contains("advance beyond tombstone"));
        sqlx::query(
            "INSERT INTO channels \
             (channel_id, name, protocol, enabled, config, revision) \
             VALUES (8, 'revisioned-recreate', 'modbus_tcp', 0, '{}', 3)",
        )
        .execute(&pool)
        .await
        .unwrap();
        assert_eq!(
            sqlx::query_scalar::<_, i64>("SELECT revision FROM channels WHERE channel_id = 8")
                .fetch_one(&pool)
                .await
                .unwrap(),
            3,
            "recreation must explicitly advance beyond the delete tombstone"
        );
        assert_eq!(
            sqlx::query(
                "UPDATE channels SET name = 'stale-cas' WHERE channel_id = 8 AND revision = 1"
            )
            .execute(&pool)
            .await
            .unwrap()
            .rows_affected(),
            0,
            "a stale CAS token must not match the recreated entity"
        );
    }

    #[tokio::test]
    async fn exhausted_channel_tombstone_rejects_recreation_before_insert() {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        init_io_schema(&pool).await.unwrap();
        sqlx::query(
            "INSERT INTO channel_revision_tombstones (channel_id, last_revision) \
             VALUES (9, 9223372036854775807)",
        )
        .execute(&pool)
        .await
        .unwrap();

        let error = sqlx::query(
            "INSERT INTO channels (channel_id, name, protocol, enabled, config) \
             VALUES (9, 'exhausted-recreate', 'modbus_tcp', 0, '{}')",
        )
        .execute(&pool)
        .await
        .expect_err("an exhausted identity must not be recreated");
        assert!(error.to_string().contains("advance beyond tombstone"));
        assert_eq!(
            sqlx::query_scalar::<_, i64>("SELECT COUNT(*) FROM channels WHERE channel_id = 9")
                .fetch_one(&pool)
                .await
                .unwrap(),
            0,
            "the BEFORE guard must reject the row itself"
        );
    }

    #[tokio::test]
    async fn test_init_automation_schema() {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        init_automation_schema(&pool).await.unwrap();

        // Verify tables exist
        let result: (i64,) =
            sqlx::query_as("SELECT COUNT(*) FROM sqlite_master WHERE type='table'")
                .fetch_one(&pool)
                .await
                .unwrap();

        // Should have 6 tables: service_config, sync_metadata, channels, instances,
        // measurement_routing, action_routing
        assert!(
            result.0 >= 6,
            "Expected at least 6 tables, found {}",
            result.0
        );
        assert_eq!(
            sqlx::query_scalar::<_, i64>(
                "SELECT revision FROM configuration_revisions \
                 WHERE scope = 'logical_routing'",
            )
            .fetch_one(&pool)
            .await
            .unwrap(),
            1
        );
    }

    #[tokio::test]
    async fn logical_routing_trigger_helper_rejects_a_missing_physical_target() {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        init_automation_schema(&pool).await.unwrap();
        init_io_schema(&pool).await.unwrap();
        install_logical_routing_integrity_triggers(&pool)
            .await
            .unwrap();

        sqlx::query(
            "INSERT INTO instances (instance_id, instance_name, product_name) \
             VALUES (7, 'fixture', 'ExampleDevice')",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query(
            "INSERT INTO channels (channel_id, name, protocol, enabled) \
             VALUES (3, 'fixture-channel', 'modbus_tcp', 0)",
        )
        .execute(&pool)
        .await
        .unwrap();

        let error = sqlx::query(
            "INSERT INTO measurement_routing \
             (instance_id, instance_name, measurement_id, channel_id, channel_type, channel_point_id) \
             VALUES (7, 'fixture', 1, 3, 'T', 99)",
        )
        .execute(&pool)
        .await
        .expect_err("routing integrity must reject a missing physical point");
        assert!(
            error
                .to_string()
                .contains("matching instance and T/S physical target"),
            "unexpected error: {error}"
        );
    }

    #[tokio::test]
    async fn test_init_rules_schema() {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        init_rules_schema(&pool).await.unwrap();

        // Verify tables exist
        let result: (i64,) =
            sqlx::query_as("SELECT COUNT(*) FROM sqlite_master WHERE type='table'")
                .fetch_one(&pool)
                .await
                .unwrap();

        // Should have 4 tables: service_config, sync_metadata, rules, rule_history
        assert!(
            result.0 >= 4,
            "Expected at least 4 tables, found {}",
            result.0
        );
        assert_eq!(
            sqlx::query_scalar::<_, i64>(
                "SELECT revision FROM configuration_revisions \
                 WHERE scope = 'automation_rules'",
            )
            .fetch_one(&pool)
            .await
            .unwrap(),
            1
        );
    }
}
