use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .ok_or("CARGO_MANIFEST_DIR is required to embed the SunSpec model catalog")?,
    );
    let out_dir = PathBuf::from(
        env::var_os("OUT_DIR").ok_or("OUT_DIR is required to embed the SunSpec model catalog")?,
    );

    generate_sunspec_models(&manifest_dir, &out_dir)
}

fn generate_sunspec_models(
    manifest_dir: &Path,
    out_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    const RELATIVE_MODEL_DIRECTORY: &str = "src/protocols/sunspec/models/json";

    let sunspec_dir = manifest_dir.join(RELATIVE_MODEL_DIRECTORY);
    let destination = out_dir.join("sunspec_models.rs");

    println!("cargo:rerun-if-changed={RELATIVE_MODEL_DIRECTORY}");

    let mut entries = Vec::new();
    for entry in fs::read_dir(&sunspec_dir)? {
        let entry = entry?;
        let file_name = entry
            .file_name()
            .into_string()
            .map_err(|name| format!("SunSpec catalog contains a non-UTF-8 filename: {name:?}"))?;
        if !entry.file_type()?.is_file() {
            return Err(
                format!("SunSpec catalog entry is not a regular file: {file_name:?}").into(),
            );
        }
        let Some(id_text) = file_name
            .strip_prefix("model_")
            .and_then(|name| name.strip_suffix(".json"))
        else {
            return Err(format!("unexpected SunSpec catalog file: {file_name:?}").into());
        };
        let id = id_text
            .parse::<u16>()
            .map_err(|error| format!("invalid SunSpec model filename {file_name:?}: {error}"))?;
        entries.push((id, file_name));
    }
    entries.sort_unstable_by_key(|(id, _)| *id);

    if entries.windows(2).any(|pair| pair[0].0 == pair[1].0) {
        return Err("SunSpec catalog contains duplicate model identifiers".into());
    }
    if entries.is_empty() {
        return Err(format!("no SunSpec model JSON found in {}", sunspec_dir.display()).into());
    }

    let mut generated = String::from(
        "// Auto-generated by services/io/build.rs — do not edit\n\
         pub static SUNSPEC_MODELS: &[(u16, &str)] = &[\n",
    );
    for (id, file_name) in entries {
        generated.push_str(&format!(
            "    ({id}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/{RELATIVE_MODEL_DIRECTORY}/{file_name}\"))),\n"
        ));
    }
    generated.push_str("];\n");
    fs::write(destination, generated)?;
    Ok(())
}
